#!/usr/bin/env python3
"""
Build the master thesis: PUBLISHABLE core + cross-cultural + images + appendix list.
Run from: content/research/unjustjustice/master_thesis/
Output: body_parts/*.tex, body.tex; then compile master.tex
"""
import os
import subprocess
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
UNJUST = os.path.normpath(os.path.join(BASE, ".."))
PUBLISHABLE = os.path.join(UNJUST, "PUBLISHABLE")
CULTURAL = os.path.join(UNJUST, "constructed_guilt_cross_cultural_data_analysis")

# PUBLISHABLE MDs in order (main body)
MD_ORDER = [
    "EXECUTIVE_SUMMARY.md",
    "CONSTRUCTED_GUILT_FULL_THESIS.md",
    "INSTITUTIONAL_NEGLIGENCE_SUPPLEMENT.md",
    "JUSTICE_PARADIGM_SHIFT_SUPPLEMENT.md",
    "NEUROIMAGING_EVIDENCE_SUPPLEMENT.md",
    "PERFECT_CASE_SYNTHESIS.md",
]

def run(cmd, cwd=None):
    r = subprocess.run(cmd, shell=True, cwd=cwd or BASE, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr or r.stdout, file=sys.stderr)
    return r.returncode == 0

def main():
    os.makedirs(os.path.join(BASE, "body_parts"), exist_ok=True)

    # 1. Convert each PUBLISHABLE MD to LaTeX
    for md in MD_ORDER:
        src = os.path.join(PUBLISHABLE, md)
        if not os.path.isfile(src):
            print("Skip (not found):", src)
            continue
        out = os.path.join(BASE, "body_parts", md.replace(".md", ".tex"))
        if run(f'pandoc "{src}" -f markdown -t latex -o "{out}" --wrap=preserve'):
            print("Converted:", md)
            # Replace Unicode box-drawing in verbatim so LaTeX compiles without unicode errors
            with open(out, "r", encoding="utf-8") as f:
                t = f.read()
            for u, a in [
                ("\u2500", "-"), ("\u2502", "|"), ("\u250c", "+"), ("\u2510", "+"),
                ("\u2514", "+"), ("\u2518", "+"), ("\u252c", "+"), ("\u2534", "+"),
                ("\u2588", "#"), ("\u2713", "[Y]"), ("\u25bc", "(v)"),
                ("\u2260", "$\\\\neq$"),
            ]:
                t = t.replace(u, a)
            # Replace fragile longtable column specs so pdflatex works (avoid \real)
            import re
            t = re.sub(
                r"p\{\(\\linewidth - \d+\\tabcolsep\) \* \\real\{[0-9.]+\}\}",
                "p{0.22\\\\linewidth}",  # safe width for multi-column tables
                t,
            )
            with open(out, "w", encoding="utf-8") as f:
                f.write(t)
        else:
            print("Pandoc failed for:", md)

    # 2. Cross-cultural section from cultural_analysis.txt
    cultural_txt = os.path.join(CULTURAL, "cultural_analysis.txt")
    cultural_tex = os.path.join(BASE, "body_parts", "cultural_section.tex")
    if os.path.isfile(cultural_txt):
        with open(cultural_txt, "r", encoding="utf-8", errors="replace") as f:
            raw = f.read()
        raw = raw.replace("\uFFFD", "?")
        for c, r in [("\\", "\\textbackslash "), ("&", "\\&"), ("%", "\\%"), ("$", "\\$"), ("#", "\\#"), ("_", "\\_"), ("{", "\\{"), ("}", "\\}")]:
            raw = raw.replace(c, r)
        with open(cultural_tex, "w", encoding="utf-8") as f:
            f.write("\\chapter{Cross-Cultural Variation in Truthful Speech}\n")
            f.write("\\label{ch:cultural}\n\n")
            f.write("\\begin{figure}[htbp]\n\\centering\n")
            f.write("\\includegraphics[width=0.85\\linewidth]{cross-cultural-falso-possitive}\n")
            f.write("\\caption{Cross-cultural false positive rates (credibility assessment).}\n\\end{figure}\n\n")
            f.write("\\begin{verbatim}\n")
            f.write(raw)
            f.write("\n\\end{verbatim}\n")
        print("Wrote:", cultural_tex)

    # 3. Write body.tex that \input s all parts in order
    parts = []
    for md in MD_ORDER:
        tex = md.replace(".md", ".tex")
        path = os.path.join("body_parts", tex)
        if os.path.isfile(os.path.join(BASE, path)):
            parts.append(f"\\input{{{path}}}")
    if os.path.isfile(os.path.join(BASE, "body_parts", "cultural_section.tex")):
        parts.append("\\input{body_parts/cultural_section.tex}")
    body_tex = os.path.join(BASE, "body.tex")
    with open(body_tex, "w", encoding="utf-8") as f:
        f.write("% Master thesis body — generated by build_master.py\n\n")
        f.write("\n\n".join(parts))
    print("Wrote:", body_tex)

if __name__ == "__main__":
    main()
